version: "3.0"
networks:
  tier1:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.172.1.0/24"
    internal: false
  tier4:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.172.4.0/24"
    internal: true
volumes:
  # Persist service's host keys (prevents MITM warnings).
  config-ssh:
    driver: "local"
services:
  # Apache PHP web server
  httpd:
    build:
      args:
        IMAGE: "jdeathe/centos-ssh-apache-php:1.13.2"
        PACKAGE_NAME: "app"
        PACKAGE_PATH: "/opt/app"
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - "redis"
    environment:
      # APACHE_CUSTOM_LOG_LOCATION: "var/log/apache_access_log"
      # APACHE_ERROR_LOG_LOCATION: "var/log/apache_error_log"
      APACHE_CUSTOM_LOG_LOCATION: "/dev/stdout"
      APACHE_ERROR_LOG_LOCATION: "/dev/stderr"
      APACHE_ERROR_LOG_LEVEL: "info"
      # Maintenance feature requires rewrite_module module.
      APACHE_LOAD_MODULES: "rewrite_module"
      APACHE_MOD_SSL_ENABLED: "true"
      APACHE_MPM: "prefork"
      APACHE_OPERATING_MODE: "development"
      APACHE_SERVER_NAME: "php-hello-world.dev.local"
      APACHE_SSL_CERTIFICATE: "${APACHE_SSL_CERTIFICATE}"
      # XDebug IDE key.
      DBGP_IDEKEY: "${DBGP_IDEKEY}"
      PHP_OPTIONS_SESSION_NAME: "php-hello-world"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "redis"
      PHP_OPTIONS_SESSION_SAVE_PATH: "redis:6379"
      # Enable sshd
      ENABLE_SSHD_WRAPPER: "true"
      ENABLE_SSHD_BOOTSTRAP: "true"
      SSH_AUTHORIZED_KEYS: "${SSH_AUTHORIZED_KEYS}"
      SSH_SUDO: "ALL=(ALL) NOPASSWD:ALL"
      SSH_USER: "${SSH_USER}"
    networks:
      - "tier1"
      - "tier4"
    ports:
      - "9022:22"
      - "80:80"
      - "443:443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    volumes:
      - "config-ssh:/etc/ssh"
      # Uncomment to mount local working directories into the running container
      # - "./public:/opt/app/public:cached"
      # - "./src:/opt/app/src:cached"
      # - "./var/log:/opt/app/var/log:cached"
  # Session store
  redis:
    image: "jdeathe/centos-ssh-redis:1.2.0"
    environment:
      REDIS_MAXMEMORY: "32mb"
    networks:
      tier4:
        aliases:
          - "redis"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
