version: "3.0"
services:
  httpd:
    build:
      args:
        IMAGE: "jdeathe/centos-ssh-apache-php-fcgi:2.2.2"
    environment:
      APACHE_MPM: "worker"
  redis:
    image: "jdeathe/centos-ssh-redis:3.1.0"
