version: "3.0"
networks:
  tier1:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.172.1.0/24"
    internal: false
  tier4:
    driver: "bridge"
    ipam:
      config:
        - subnet: "172.172.4.0/24"
    internal: true
volumes:
  # Persist service's host keys (prevents MITM warnings).
  config-ssh:
    driver: "local"
services:
  # Apache PHP web server
  httpd:
    build:
      args:
        IMAGE: "jdeathe/centos-ssh-apache-php:1.12.0"
        PACKAGE_NAME: "app"
        PACKAGE_PATH: "/opt/app"
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - "memcached_1"
      - "memcached_2"
    environment:
      APACHE_ERROR_LOG_LEVEL: "info"
      # Maintenance feature requires rewrite_module module.
      APACHE_LOAD_MODULES: "rewrite_module"
      APACHE_MOD_SSL_ENABLED: "true"
      APACHE_MPM: "prefork"
      APACHE_OPERATING_MODE: "development"
      APACHE_SERVER_NAME: "php-hello-world.dev.local"
      APACHE_SSL_CERTIFICATE: "${APACHE_SSL_CERTIFICATE}"
      # XDebug IDE key.
      DBGP_IDEKEY: "${DBGP_IDEKEY}"
      PHP_OPTIONS_SESSION_NAME: "php-hello-world"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached_1:11211:50,memcached_2:11211:50"
      SSH_AUTHORIZED_KEYS: "${SSH_AUTHORIZED_KEYS}"
      SSH_AUTOSTART_SSHD: "true"
      SSH_AUTOSTART_SSHD_BOOTSTRAP: "true"
      SSH_SUDO: "ALL=(ALL) NOPASSWD:ALL"
      SSH_USER: "${SSH_USER}"
    networks:
      - "tier1"
      - "tier4"
    ports:
      - "9022:22"
      - "80:80"
      - "443:443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    volumes:
      - "config-ssh:/etc/ssh"
      # Uncomment to mount local working directories into the running container
      # - "./public:/opt/app/public:cached"
      # - "./src:/opt/app/src:cached"
      - "./var/log:/opt/app/var/log:cached"
  # Memcached session store
  memcached_1:
    image: "jdeathe/centos-ssh-memcached:1.3.1"
    environment:
      MEMCACHED_CACHESIZE: "32"
    networks:
      tier4:
        aliases:
          - "memcached_1"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
  memcached_2:
    image: "jdeathe/centos-ssh-memcached:1.3.1"
    environment:
      MEMCACHED_CACHESIZE: "32"
    networks:
      tier4:
        aliases:
          - "memcached_2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
